AWSTemplateFormatVersion: '2010-09-09'

Description: Supplier ingestion pipeline learning project

Resources:

  DataBucket:
    Type: AWS::S3::Bucket


  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: ReadFromS3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${DataBucket.Arn}/*'


  ProcessingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: supplier-ingestion-processor-dev
      Runtime: python3.13
      Handler: handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128
      Code:
        S3Bucket: !Ref DataBucket
        S3Key: deployment/lambda.zip


  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessingLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt DataBucket.Arn
Outputs:

  DataBucketName:
    Description: S3 bucket used by the supplier ingestion pipeline
    Value: !Ref DataBucket

  ProcessingLambdaName:
    Description: Supplier ingestion Lambda function
    Value: !Ref ProcessingLambda